# Generated by Django 4.2.2 on 2023-06-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_member_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=255)),
                ('csummary', models.TextField()),
                ('cimg', models.ImageField(upload_to='courseimages')),
            ],
        ),
    ]
