# Generated by Django 4.2.2 on 2023-06-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='heading',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
